import express from 'express';
import { protect, authorize } from '../middlewares/authMiddleware.js';
import { createFaculty, getAllFaculty, updateFaculty, deleteFaculty } from '../controllers/facultyController.js';
const router = express.Router();
router.use(protect, authorize('ADMIN'));
router.post('/', createFaculty);
router.get('/', getAllFaculty);
router.put('/:id', updateFaculty);
router.delete('/:id', deleteFaculty);
export default router;